version: '3'

services:
  server:
    build: ./server
    container_name: mlops_zoomcamp_homework_2_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: sh -c "mlflow server --backend-store-uri sqlite:///${DB_NAME} --default-artifact-root ./${ARTIFACT_STORAGE} --host 0.0.0.0 --port ${SERVER_PORT}"
  predictor:
    build: ./predictor
    container_name: mlops_zoomcamp_homework_2_predictor
    depends_on:
      - server